# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.buildconfig=true
android.defaults.buildfeatures.renderscript=false
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
android.enableR8.fullMode=true
android.nonTransitiveRClass=true
android.useAndroidX=true
kapt.include.compile.classpath=false
kapt.incremental.apt=false
kapt.use.worker.api=false
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvm.options=-Xmx512m -Xms128m
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.daemon=true
org.gradle.daemon.idletimeout=10800000
org.gradle.jvmargs=-Xmx2048m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 \
  --add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
org.gradle.parallel=true
room.expandProjection=true
room.incremental=true
room.schemaLocation=schemas
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
systemProp.user.country=US
systemProp.user.language=en
