pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        maven { url 'https://jitpack.io' }
        // Use a regional mirror if Maven Central is blocked
        maven { url 'https://maven.aliyun.com/repository/public' } // For China
        maven { url 'https://repo1.maven.org/maven2' }             // Direct Maven Central
        mavenCentral()
    
    }

}

rootProject.name = "NovelVerse"
include ':app'
